#!/bin/bash

HAYSTACK=$(which php);
NEEDLE='not found'
PHP_VERSION=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
VERSION=${PHP_VERSION:0:1}

echo "Hello, $(whoami)!"

if [[ "$HAYSTACK" == *"$NEEDLE"* ]] || [[ $VERSION -lt 8 ]];
then
  # PHP not installed...
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  /bin/bash command brew install php
fi

/bin/bash command /usr/local/bin/clair hello