name: Zip and upload latest to S3
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Make artifact directory
      run: mkdir -p ./artifacts/${{ github.repository }}

    - name: Create Zip File
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r /artifacts/helloclair.zip .

    - name: Push Zip to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        SOURCE_DIR: './artifacts'
        DEST_DIR: '/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}