name: Zip and upload latest to S3
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Make artifact directory
      run: mkdir -p ./artifacts

    - name: Create Zip File
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r ./artifacts/helloclair.zip ./builds/clair ./helloclair

    - name: Push Zip to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        SOURCE_DIR: './artifacts'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}